modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
    modId="examplemod"
    version="${file.jarVersion}"
    logoFile="logo.png"
    itemIcon = "minecraft:dirt"
    configBackground = "minecraft:textures/block/dirt.png"
    authors="LaGz4643"
    credits=""
    #displayTest="IGNORE_SERVER_VERSION" - server side only mod
    #displayTest="IGNORE_ALL_VERSION" - client side only mod - delete both for normal content mod
    displayName="Example Mod"
    description='''Example Description.'''

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.examplemod]]
#    modId="exampledependency"
#    mandatory=true
#    versionRange="[minversion,)"
#    ordering="NONE" # BEFORE or AFTER required to be specified if mandatory=false
#    side="BOTH"