modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
    modId="bedrock_cauldrons"
    version="${file.jarVersion}"
    logoFile="logo.png"
    itemIcon = "minecraft:cauldron"
    configBackground = "minecraft:textures/block/dirt.png"
    authors="LaGz"
    credits=""
    displayName="Bedrock Cauldrons"
    description='''Adds potion and dye cauldrons from Minecraft: Bedrock Edition.'''

[[dependencies.bedrock_cauldrons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrock_cauldrons]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.bedrock_cauldrons]]
#    modId="exampledependency"
#    mandatory=true
#    versionRange="[minversion,)"
#    ordering="NONE" # BEFORE or AFTER required to be specified if mandatory=false
#    side="BOTH"